// Date: 2018/04/26 13:29:40
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer bottom;
    ModelRenderer front;
    ModelRenderer back;
    ModelRenderer side1;
    ModelRenderer side2;
    ModelRenderer top;
    ModelRenderer pomp1;
    ModelRenderer pomp2;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      bottom = new ModelRenderer(this, 49, 0);
      bottom.addBox(-3F, 0F, -7F, 10, 1, 14);
      bottom.setRotationPoint(0F, 0F, 0F);
      bottom.setTextureSize(128, 64);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
      front = new ModelRenderer(this, 0, 42);
      front.addBox(-3F, -8F, -8F, 10, 9, 1);
      front.setRotationPoint(0F, 0F, 0F);
      front.setTextureSize(128, 64);
      front.mirror = true;
      setRotation(front, 0F, 0F, 0F);
      back = new ModelRenderer(this, 23, 42);
      back.addBox(-3F, -8F, 7F, 10, 9, 1);
      back.setRotationPoint(0F, 0F, 0F);
      back.setTextureSize(128, 64);
      back.mirror = true;
      setRotation(back, 0F, 0F, 0F);
      side1 = new ModelRenderer(this, 0, 16);
      side1.addBox(7F, -8F, -8F, 1, 9, 16);
      side1.setRotationPoint(0F, 0F, 0F);
      side1.setTextureSize(128, 64);
      side1.mirror = true;
      setRotation(side1, 0F, 0F, 0F);
      side2 = new ModelRenderer(this, 35, 16);
      side2.addBox(-4F, -8F, -8F, 1, 9, 16);
      side2.setRotationPoint(0F, 0F, 0F);
      side2.setTextureSize(128, 64);
      side2.mirror = true;
      setRotation(side2, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 0);
      top.addBox(-3F, 0F, -7F, 10, 1, 14);
      top.setRotationPoint(0F, -7F, 0F);
      top.setTextureSize(128, 64);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      pomp1 = new ModelRenderer(this, 46, 42);
      pomp1.addBox(-6F, -1F, -1F, 2, 2, 3);
      pomp1.setRotationPoint(0F, 0F, 0F);
      pomp1.setTextureSize(128, 64);
      pomp1.mirror = true;
      setRotation(pomp1, 0F, 0F, 0F);
      pomp2 = new ModelRenderer(this, 46, 48);
      pomp2.addBox(-7F, 0F, 0F, 1, 1, 1);
      pomp2.setRotationPoint(0F, 0F, 0F);
      pomp2.setTextureSize(128, 64);
      pomp2.mirror = true;
      setRotation(pomp2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bottom.render(f5);
    front.render(f5);
    back.render(f5);
    side1.render(f5);
    side2.render(f5);
    top.render(f5);
    pomp1.render(f5);
    pomp2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
